account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path("register/", views.register, name="register"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from smartfields import fields
from smartfields.dependencies import FileDependency
from smartfields.processors import ImageProcessor


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = fields.ImageField(upload_to='products/%Y/%m/%d', blank=True, dependencies=[
        FileDependency(processor=ImageProcessor(
            format='JPEG', scale={'max_width': 300, 'max_height': 300}))
    ])
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    # image = fields.ImageField(dependencies=[
    #     FileDependency(processor=ImageProcessor(
    #         format='JPEG', scale={'max_width': 300, 'max_height': 300}))
    # ])

shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category
from .models import Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/product_detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/710afe8ed2.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js" integrity="sha256-JirYRqbf+qzfqVtEE4GETyHlAbiCpC005yBTa4rj6xg=" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="{% static 'css/base.css' %}" type="text/css" rel="stylesheet">


    <title>Shop v2</title>
  </head>
  <body>
  <div class="header-nav shadow-sm">
    <div class="container top-header">
      <div class="row">
        <div class="col-sm">
          <p class="contact">Email || Phone Number</p>
        </div>
        <div class="col-sm">
        </div>
        <div class="col-sm r-links">
            {% if user.is_authenticated %}
            <!-- Default dropup button -->
              <a href="#" class="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Witaj, {{ user.first_name }} {{ user.last_name }}</a>
              <div class="dropdown-menu dropright">
                <a class="dropdown-item" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart mr-2"></i>Cart</a>
                <div class="dropdown-divider"></div>
                
                <a class="dropdown-item" href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt mr-2"></i>Logout</a>
              </div>
            {% else %}
            <a href="{% url 'account:login' %}"><i class="fas fa-door-open"></i>Login</a>
            <a href="{% url 'account:register' %}"><i class="fas fa-sign-in-alt"></i>Create an Account</a>
            <a href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>Cart</a>
            {% endif %}
        </div>
      </div>
    </div>
    <div class="container header">
      <div class="row">
        <div class="col-sm-8 col-md-8 col-6">
            <div class="brand-logo">
                <img src="#" alt="">
            </div>
        </div>
        <div class="col-sm-4">
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
       <ul class="nav justify-content-center mb-4">
          <li class="nav-item">
            <a class="nav-link active" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:product_list' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Contact</a>
          </li>
        </ul>
    </div>
  </div>
  <div class="container messages">
      {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success'%}
                <div class="alert alert-success alert-dismissible" role="alert">{{message}}</div>
                {% elif message.tags == 'info'%}
                <div class="alert alert-info alert-dismissible" role="alert">{{message}}</div>
                {% elif message.tags == 'warning'%}
                <div class="alert alert-warning alert-dismissible" role="alert">{{message}}</div>
                {% elif message.tags == 'error'%}
                <div class="alert alert-error alert-dismissible" role="alert">{{message}}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
  </div>
  <div class="main-content">
    {% block content %}
    {% endblock %}
  </div>
  <footer id="sticky-footer" class="py-4 bg-dark text-white mt-4">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="text/javascript">

      </script>

  </body>
</html>